Repository oonisidesu/webserv, pull requests merged in 2025-04, with the labels that each got.

#14 7 sharedptrを使うようにする
  src/core/main.cpp
  src/event/epoll.cpp
  src/event/epoll.hpp
  src/event/tagged_epoll_event.hpp
  src/socket/server.cpp
  toolbox/shared.hpp
  toolbox/string.cpp
Labels: task

#18 17-rpレビュー自動依頼設定が動いていない
  .github/CODEOWNERS
Labels: bug

#28 20 リクエスト処理
  src/core/main.cpp
  src/event/epoll.cpp
  src/event/epoll.hpp
  src/event/tagged_epoll_event.hpp
  src/http/http_namespace.cpp
  src/http/http_namespace.hpp
  src/http/request/http_fields.cpp
  src/http/request/http_fields.hpp
  src/http/request/http_request.hpp
  src/http/request/parse_test.cpp
  src/http/request/request_parser.cpp
  src/http/request/request_parser.hpp
  src/socket/client.cpp
  src/socket/client.hpp
  src/socket/server.cpp
  src/socket/server.hpp
  toolbox/shared.hpp
  toolbox/string.cpp
  toolbox/string.hpp
Labels: wontfix, task
